--quiet --mode gtp --gtp-input capture.tst
--quiet --mode gtp --gtp-input connect.tst
--quiet --mode gtp --gtp-input connect_rot.tst
--quiet --mode gtp --gtp-input connection.tst
--quiet --mode gtp --gtp-input connection_rot.tst
--quiet --mode gtp --gtp-input cutstone.tst
--quiet --mode gtp --gtp-input dniwog.tst
